'use strict';
/*
 * Walk a directory (optionally glob-filtered), count tokens per file, aggregate.
 * No external deps — uses fs walking + simple glob matching so the skill stays
 * portable. Returns { files:[{path, tokens, bytes}], total, counter }.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const toPosix = (p) => p.replace(/\\/g, '/');

// Set of git-ignored paths under `root` (one batched call), as POSIX-slash
// strings — callers compare with toPosix(file). Empty if git is missing or
// `root` isn't a repo, so behavior degrades to "count all". Lets scans/skill
// analysis skip build output + working files the user already chose to ignore,
// instead of flagging them as orphan docs.
// (Paths are normalized to forward slashes: Windows git C-quotes backslash
// paths in the output, which would never match the raw inputs.)
function gitIgnored(root, absPaths) {
  if (!absPaths.length) return new Set();
  try {
    const out = execFileSync('git', ['-C', root, 'check-ignore', '--stdin'],
      { input: absPaths.map(toPosix).join('\n'), encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] });
    return new Set(out.split(/\r?\n/).filter(Boolean));
  } catch (e) {
    // exit 1 (nothing ignored) or 128 (not a repo) → throws; salvage any stdout
    return new Set(e && e.stdout ? String(e.stdout).split(/\r?\n/).filter(Boolean) : []);
  }
}

// directories never worth counting (deps, build output, VCS, generated artifacts,
// and git worktrees — which duplicate the whole tree and swamp real source)
const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', 'out', '.next', '.nuxt', '.cache',
  'coverage', '.venv', 'venv', '__pycache__', '.idea', '.vscode', '.turbo',
  'worktrees', '.worktrees', 'target', 'vendor', '.svelte-kit', '.parcel-cache',
  // generated by tools in this ecosystem
  'code-metrics-out', '.playwright-cli', '.playwright', 'playwright-report',
  'test-results', '.wrangler', '.uploads',
  // controlled-browser profiles (thousands of extension JS files — pure noise)
  '.browser-profile', '.chrome-profile', '.chrome-dev-profile', '.chrome-profiles',
]);

// treat as text by extension (avoid tokenizing binaries)
const TEXT_EXT = new Set([
  '.md', '.mdx', '.txt', '.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx',
  '.json', '.yaml', '.yml', '.toml', '.py', '.rs', '.go', '.java', '.kt',
  '.c', '.h', '.cpp', '.cs', '.rb', '.php', '.sh', '.ps1', '.html', '.css',
  '.xml', '.sql', '.csv', '.ini', '.env', '.gradle', '.svelte', '.vue',
]);

function globToRegExp(glob) {
  // tokenize so inserted regex (with its own * / ?) isn't re-substituted
  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === '*') {
      if (glob[i + 1] === '*') {
        i++;
        if (glob[i + 1] === '/') { i++; re += '(?:.*/)?'; } // **/ -> optional dirs
        else re += '.*';                                     // ** -> anything
      } else re += '[^/]*';                                  // * -> within a segment
    } else if (c === '?') re += '[^/]';
    else re += c.replace(/[.+^${}()|[\]\\]/, '\\$&');
  }
  return new RegExp('^' + re + '$');
}

function* walk(root) {
  let entries;
  try { entries = fs.readdirSync(root, { withFileTypes: true }); }
  catch { return; }
  for (const e of entries) {
    const full = path.join(root, e.name);
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name)) continue;
      yield* walk(full);
    } else if (e.isFile()) {
      yield full;
    }
  }
}

// files above this are virtually always generated/minified (huge HTML galleries,
// bundled JS, vendored data). Tokenizing them is the main scan bottleneck and
// their counts aren't actionable. Skipped but tallied — never silently dropped.
const MAX_FILE_BYTES = 2 * 1024 * 1024; // 2 MB

function scan(target, { counter, glob, includeAll = false, maxBytes = MAX_FILE_BYTES } = {}) {
  const stat = fs.statSync(target);
  const root = stat.isDirectory() ? target : path.dirname(target);
  const re = glob ? globToRegExp(glob) : null;

  let candidates = stat.isFile() ? [target] : [...walk(target)];
  // drop files the repo already gitignores (build output, working/generated files)
  if (!stat.isFile()) {
    const ignored = gitIgnored(root, candidates);
    if (ignored.size) candidates = candidates.filter(f => !ignored.has(toPosix(f)));
  }
  const files = [];
  const skippedLarge = [];
  let total = 0;

  for (const file of candidates) {
    const rel = path.relative(root, file).split(path.sep).join('/');
    if (re && !re.test(rel)) continue;
    if (!includeAll && !TEXT_EXT.has(path.extname(file).toLowerCase())) continue;
    // size-gate via stat BEFORE reading, so a giant file never enters memory
    let size;
    try { size = fs.statSync(file).size; } catch { continue; }
    if (maxBytes && size > maxBytes && !stat.isFile()) {
      skippedLarge.push({ path: rel || path.basename(file), bytes: size });
      continue;
    }
    let text;
    try { text = fs.readFileSync(file, 'utf8'); } catch { continue; }
    const tokens = counter.count(text);
    total += tokens;
    files.push({ path: rel || path.basename(file), tokens, bytes: Buffer.byteLength(text) });
  }

  files.sort((a, b) => b.tokens - a.tokens);
  skippedLarge.sort((a, b) => b.bytes - a.bytes);
  return { files, total, counter: counter.name, skippedLarge };
}

module.exports = { scan, walk, gitIgnored, toPosix, globToRegExp, SKIP_DIRS, TEXT_EXT, MAX_FILE_BYTES };
